# This file configures the build for the FRONTEND service.
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'Build and Push Frontend'
  args:
    - '--context=.'
    - '--dockerfile=Dockerfile.frontend'
    - '--destination=europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'
    - '--cache=true'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'Deploy Frontend'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_FRONTEND_SERVICE}'
    - '--image'
    - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'
    - '--platform=managed'
    - '--region=${_REGION}'
    - '--allow-unauthenticated'
    - '--project=${PROJECT_ID}'

images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'

substitutions:
  _REGION: europe-west1
  _FRONTEND_SERVICE: peacock-frontend

options:
  logging: CLOUD_LOGGING_ONLY
