# This file configures the build for the BACKEND service.
steps:
  # This step uses the gcloud command-line tool to build and push the image.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Build and Push Backend'
    args:
      - 'builds'
      - 'submit'
      - './backend' # Specifies the backend directory
      - '--tag=europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-backend-service:${COMMIT_SHA}'

# This specifies the final image that Cloud Run will use for deployment.
images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-backend-service:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY