# This file configures the build for the FRONTEND service.
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'Build and Push Frontend'
  args:
    - '--context=.'
    - '--dockerfile=Dockerfile.frontend'
    - '--destination=europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'
    - '--cache=true'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'Deploy Frontend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        set -euo pipefail
        for attempt in 1 2 3; do
          if gcloud run deploy "${_FRONTEND_SERVICE}" \
            --image "europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}" \
            --platform=managed \
            --region="${_REGION}" \
            --allow-unauthenticated \
            --project="${PROJECT_ID}" \
            --port=80 \
            --quiet; then
            exit 0
          fi
          echo "Deploy attempt ${attempt} failed; retrying in 10s..." >&2
          sleep 10
        done
        echo "Deployment failed after 3 attempts." >&2
        exit 1

substitutions:
  _REGION: europe-west1
  _FRONTEND_SERVICE: peacock-frontend

options:
  logging: CLOUD_LOGGING_ONLY
