# This file configures the build for the FRONTEND service.
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Frontend'
  args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'
    - '.' # Build from the root directory
    - '-f'
    - 'Dockerfile.frontend' # Use the frontend-specific Dockerfile

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Frontend'
  args:
    - 'push'
    - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'

images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/peacock-backend-repo/peacock-frontend:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY