const products = [
  {
    id: 1,
    name: 'Royal Blue Lehenga',
    category: 'women',
    description: 'A stunning lehenga with intricate gold embroidery.',
    stylingNotes: 'Pair with polki jewellery and kundan bangles.',
    imageUrls: ['https://picsum.photos/seed/lehenga/400/500'],
    buyPrice: 450,
    rentPrice: 90,
    sellerEmail: 'seller@peacock.com',
  },
  {
    id: 2,
    name: 'Emerald Green Sherwani',
    category: 'men',
    description: 'Elegant silk sherwani for weddings and special occasions.',
    stylingNotes: 'Compliment with mojris and a pastel safa.',
    imageUrls: ['https://picsum.photos/seed/sherwani/400/500'],
    buyPrice: 500,
    rentPrice: 100,
    sellerEmail: 'seller@peacock.com',
  },
  {
    id: 3,
    name: 'Ruby Red Saree',
    category: 'women',
    description: 'Classic Banarasi silk saree with a modern twist.',
    stylingNotes: 'Style with a sleek bun and emerald choker.',
    imageUrls: ['https://picsum.photos/seed/saree/400/500'],
    buyPrice: 350,
    rentPrice: 75,
  },
  {
    id: 4,
    name: 'Golden Jhumkas',
    category: 'jwellery',
    description: 'Traditional temple jewellery-style earrings.',
    stylingNotes: 'Let them shine with a low bun and silk saree.',
    imageUrls: ['https://picsum.photos/seed/jhumkas/400/500'],
    buyPrice: 80,
    rentPrice: 20,
  },
  {
    id: 5,
    name: 'Boys Kurta Pajama Set',
    category: 'kids-boys',
    description: 'Comfortable and stylish cotton kurta set for boys.',
    stylingNotes: 'Add a Nehru jacket for celebrations.',
    imageUrls: ['https://picsum.photos/seed/kurta/400/500'],
    buyPrice: 120,
    rentPrice: 30,
  },
  {
    id: 6,
    name: 'Girls Anarkali Dress',
    category: 'kids-girls',
    description: 'Flowy and vibrant anarkali for young girls.',
    stylingNotes: 'Pair with pearl hair clips.',
    imageUrls: ['https://picsum.photos/seed/anarkali/400/500'],
    buyPrice: 150,
    rentPrice: 40,
  },
  {
    id: 7,
    name: 'Embroidered Potli Bag',
    category: 'handbags',
    description: 'A beautiful potli bag to complete your traditional look.',
    stylingNotes: 'Match with gold bangles.',
    imageUrls: ['https://picsum.photos/seed/potli/400/500'],
    buyPrice: 60,
    rentPrice: 15,
  },
  {
    id: 8,
    name: 'Classic Nehru Jacket',
    category: 'men',
    description: 'A versatile jacket that can be paired with any kurta.',
    stylingNotes: 'Best layered over ivory kurtas.',
    imageUrls: ['https://picsum.photos/seed/nehru/400/500'],
    buyPrice: 180,
    rentPrice: 45,
  },
  {
    id: 9,
    name: 'Silver Diya Set',
    category: 'pooja-items',
    description: 'Exquisite silver-plated diyas for your pooja room.',
    stylingNotes: 'Set on brass thalis with fresh flowers.',
    imageUrls: ['https://picsum.photos/seed/diya/400/500'],
    buyPrice: 150,
    rentPrice: 35,
  },
  {
    id: 10,
    name: 'Embroidered Mojaris',
    category: 'shoes',
    description: 'Handcrafted traditional mojaris with intricate threadwork.',
    stylingNotes: 'Pair with silk dhotis or jeans alike.',
    imageUrls: ['https://picsum.photos/seed/mojari/400/500'],
    buyPrice: 95,
    rentPrice: 25,
  },
  {
    id: 11,
    name: 'Kundan Necklace Set',
    category: 'jwellery',
    description: 'A stunning Kundan necklace with matching earrings.',
    stylingNotes: 'Let it rest on velvet blouses.',
    imageUrls: ['https://picsum.photos/seed/kundan/400/500'],
    buyPrice: 220,
    rentPrice: 55,
  },
  {
    id: 12,
    name: 'Peacock Wall Art',
    category: 'home-decor',
    description: 'Vibrant metal wall art to adorn your living space.',
    stylingNotes: 'Anchor above consoles with planters.',
    imageUrls: ['https://picsum.photos/seed/wallart/400/500'],
    buyPrice: 130,
    rentPrice: 40,
  },
];

const reviews = [
  { id: 1, productId: 1, author: 'Priya S.', location: 'New York, USA', text: 'The lehenga was absolutely breathtaking! I received so many compliments. The rental process was seamless.', rating: 5 },
  { id: 2, productId: 2, author: 'Aarav M.', location: 'London, UK', text: 'Peacock has an amazing collection. The sherwani I bought was of premium quality. Highly recommend!', rating: 5 },
  { id: 3, productId: 3, author: 'Sunita K.', location: 'Toronto, CA', text: 'I rented a saree for a family function and it was perfect. The customer service is top-notch.', rating: 4 },
  { id: 4, productId: 1, author: 'Rohan P.', location: 'Sydney, AU', text: 'Finally, a place for high-quality Indian wear abroad. My go-to for every occasion.', rating: 5 },
];

const users = [];
const orders = [];

module.exports = {
  mockProducts: products,
  mockReviews: reviews,
  mockUsers: users,
  mockOrders: orders,
};
